### ISSUE TITLE
The link in `README.md` of the `compare/` folder is not working

### ISSUE THREAD

**Issue by xie186** [brentp/bwa-meth#74]
Hi @brentp , the link here (https://copy.com/jxoJKLOhWzjz) seems not working anymore. I would like to try the performance of dragmap on BS-seq reads (https://github.com/xie186/dragmap-meth). I would like to use `bwa-meth` as a base to compare. Could you please update the link if the data is still available when you get a chance? Thanks.

**Comment by brentp** [comment]
Hi, unfortunately that data is no longer available to me. I have tried to get it from the old institution, but that is not possible.

I'm glad to see you using bwa-meth code and you're certainly welcome to do so. Perhaps, you might consider a more prominent and accurate notification of how you used bwa-meth code since the major and important parts are taken literally  from there.

**Comment by xie186** [comment]
Thank you for the quick response. Then I'll simulate the read with Sherman. 
Yes. I totally agree with you about the notification. I learned a lot while reading your code. Thank you. Do you mind if I add you as a contributor to  [dragmap-meth](https://github.com/xie186/dragmap-meth)? You can also update the READMEME.md file and codes if you have any suggestions.

**Comment by brentp** [comment]
I think adding me as a contributor is overly generous and not necessary. A more clear indication that a good portion of the code is directly copied from bwa-meth does not detract from your work, credits mine, and gives more info on the provenance.
Nice work BTW!

**Comment by xie186** [comment]
Thanks you. I'll email you about the contributor topic and how to give the provenance.
